#!/usr/bin/env bash
#Creating a script that displays from 1 to 20 in addition to:
#"bad luck from China" for the 4th loop iteration
#"bad luck from Japan" for the 9th loop iteration
#"bad luck from Italy" for the 17th loop iteration
x=1
while [ $x -le 20 ]
do
    echo "$x"
    case $x in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    ((x++))
done
