#!/usr/bin/env bash
#Creating a script that displays time for:
#display hours from 0 to 12
#display minutes from 1 to 59
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -le 59 ]
    do
	echo "$minutes"
	((minutes++))
    done
    ((hour++))
done
