#!/usr/bin/env bash
#Creating a script that display information about the file 'School'
if [ -e "School" ]
then
    echo "School file exists"

    if [ -s School ]
    then
	echo "School file is not empty"
    else
	echo "School file is empty"
    fi

    if [ -f School ]
    then
	echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
